### PR TITLE
New Text

### PR DESCRIPTION
**Pull request by jedwardwalters**
Adding Chronicle of Edessa (57.xml)

### CODE REVIEW

**Comment by jedwardwalters** [comment]
@dlschwartz Chronicle of Edessa is now done. @wsalesky said the web hooks aren't working currently on the dev server, so it will be viewable whenever those work again at:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/rec.html?id=https://syriaccorpus.org/57

**Comment by wsalesky** [comment]
@jedwardwalters @dlschwartz 
I moved it manually. It is now up on the dev server.

**Comment by jedwardwalters** [comment]
Thanks, @wsalesky!

**Comment by wsalesky** [comment]
No problem!

**Pull request merged**
